#!/bin/bash
set -euo pipefail

OUT=${1:?Usage: ./submit_fluent_surf.sh output_base input_case.cas.h5}
CASE=${2:?Usage: ./submit_fluent_surf.sh output_base input_case.cas.h5}
GX=${GX:-0}
GY=${GY:-9.81}
H=${H:-0.00495}

# To run: ./submit_fluent_surf.sh [run name] [case file] 
# inside the directory with the case file, starting data file and the NCA_PIDcontrol_linux.c file
# make executable by doing chmod +x submit_fluent_surf.sh
# Optional environment overrides:
#   FLUENT_NTASKS=8 ./submit_fluent_surf.sh run1 SYS-4.cas.h5
#   FLUENT_TIME=8:00:00 ./submit_fluent_surf.sh run1 SYS-4.cas.h5
#  To run with different gravity: GX=your_x_grav GY=your_y_grav ./submit_fluent_surf.sh my_run my_case.cas.h5

NTASKS=${FLUENT_NTASKS:-8}
TIME_LIMIT=${FLUENT_TIME:-72:00:00}
PARTITION=${FLUENT_PARTITION:-engineering}
MEM_PER_CPU=${FLUENT_MEM_PER_CPU:-1000}

SUBMIT_DIR=$(pwd)
CASE_ABS=$(readlink -f "$CASE")
CASE_LOCAL=$(basename "$CASE_ABS")

# Replace .cas.h5 with .dat.h5
DAT="${CASE%.cas.h5}.dat.h5"
DAT_ABS=$(readlink -f "$DAT")
# Strip leading directory path
DAT_LOCAL=$(basename "$DAT_ABS")

JOU="${OUT}.jou"
FINAL_CASE_DATA="${OUT}.cas.h5"
S2S_FILE="${OUT}.s2s.h5"
NEW_FOLDER="${OUT}_files"


if [[ ! -f "$CASE_ABS" ]]; then
    echo "Error: case file not found: $CASE_ABS" >&2
    exit 1
fi

if [[ ! -f "$DAT_ABS" ]]; then
    echo "Error: data file not found: $DAT_ABS" >&2
    exit 1
fi

if [[ ! -f "NCA_PIDcontrol_regression_linux.c" ]]; then
    echo "Error: NCA_PIDcontrol_regression_linux.c not found in current directory: $SUBMIT_DIR" >&2
    echo "Run this script from the directory containing NCA_PIDcontrol_regression_linux.c and your Fluent files." >&2
    exit 1
fi

if [[ -e ${NEW_FOLDER} ]]; then
    echo "Error: run folder already exists: ${NEW_FOLDER}" >&2
    echo "Please remove or choose a different output base." >&2
    exit 1
fi
mkdir -p "$NEW_FOLDER"
cd "$NEW_FOLDER"

cp "$CASE_ABS" .
cp "$DAT_ABS" .
cp ../NCA_PIDcontrol_regression_linux.c .

cat > "$JOU" <<EOF
;;; Solution Journal Script for running the NCA Fluent model in batch mode
;;; Auto-generated by submit_fluent_surf.sh
;;; Output base: ${OUT}
;;; Input case: "${CASE_ABS}"
;;; Local case file: "${CASE_LOCAL}"
;;; Gravity: GX=${GX}, GY=${GY}
;;; Gap Height: H=${H}

;; ------Compile and load UDF------------------------------------------------------
/define/user-defined/compiled-functions compile "lib_inlet_fsr" yes "NCA_PIDcontrol_regression_linux.c" "" ""
/define/user-defined/compiled-functions load "lib_inlet_fsr"

;; ------Read case file------------------------------------------------------------
/define/user-defined/auto-compile-compiled-udfs no
/file/read-case "${CASE_LOCAL}"

;; ------Set gravity---------------------------------------------------------------
/define/operating-conditions/gravity yes ${GX} ${GY}

;; ------Compute View factors------------------------------------------------------
/define/models/radiation/s2s-parameters compute-write-vf "${S2S_FILE}"

;; ------Initialize----------------------------------------------------------------
;; Initialization and patches not needed when using .dat file to initialize
;;/solve/initialize/compute-defaults/velocity-inlet inlet
;;/solve/initialize/initialize-flow
;;/solve/patch () ignition () temperature 1700
;;/solve/patch () downstream () species-3 0


;; Read previous solution for initialization
/file/read-data "${DAT_LOCAL}"

;;-------UDF setup---------------------------------------------------------
;; other RP variables should be stored in the case file and are read when the case file is read.
;; The following variables are set here to make sure they are correct.

(rp-var-define 'user/u_mean 0.15 'real #f)
/define/user-defined/execute-on-demand "check_rp_vars::lib_inlet_fsr"

;; For setups with changing gap height
;;
;; (rp-var-define 'user/h ${H} 'real #f)
;; /define/user-defined/execute-on-demand "check_h::lib_inlet_fsr"

;; ------Solve---------------------------------------------------------------------
;; Make sure derivatives are availible
/solve/set/expert no no yes no
;; Make sure species mass fraction gradients are availible
/define/models/species/save-gradients yes

;; Do 50 iterations for testing
;;/solve/iterate 50 

;; Clear ISAT table before calculation to prevent the no reaction bug
/define/models/species/clear-isat-table

;; Do 500000 max iterations for real calculation
/solve/iterate 500000

;; ------List available CGNS export scalars ---------------------------------------
;;/file/export/cgns "scalar_probe" full-domain yes yes

()
;; ------Write output case and data -----------------------------------------------
/file/write-case-data "${FINAL_CASE_DATA}"

/file/export/cgns "${OUT}" surface-select fluid pmma quartz inlet outlet wall_bottom \
wall_isolated_pmma wall_isolated_pmma_out wall_isolated_quartz wall_mass_flux wall_mass_flux-shadow \
 wall_top_channel wall_top_channel-shadow wall_top_quartz wall_upstream wall_upstream-shadow () \
yes yes \
 x-coordinate y-coordinate c5h8o2-n-deposition-rate cell-id cell-volume co2 h2o n2 o2 c5o2h8 \
 dco2-dx dco2-dy dh2o-dx dh2o-dy dn2-dx dn2-dy do2-dx do2-dy dc5o2h8-dx dc5o2h8-dy density \
 dt-dx dt-dy heat-flux pressure rad-heat-flux recon-dp-dx recon-dp-dy recon-dt-dx recon-dt-dy \
 recon-dx-velocity-dx recon-dx-velocity-dy recon-dy-velocity-dx recon-dy-velocity-dy \
 surf-incident-radiation surf-kinetic-rate-reaction-1 temperature thermal-conductivity-lam \
 thermal-diffc5o2h8 thermal-diffco2 thermal-diffh2o thermal-diffn2 thermal-diffo2 \
 vol-kinetic-rate-reaction-2 x-face-area y-face-area x-velocity y-velocity specific-heat-cp ()

;;/file/export/cgns "${OUT}" full-domain yes yes x-coordinate y-coordinate c5h8o2-n-deposition-rate cell-id cell-volume co2 h2o n2 o2 c5o2h8 dco2-dx dco2-dy dh2o-dx dh2o-dy dn2-dx dn2-dy do2-dx do2-dy dc5o2h8-dx dc5o2h8-dy density dt-dx dt-dy heat-flux pressure rad-heat-flux recon-dp-dx recon-dp-dy recon-dt-dx recon-dt-dy recon-dx-velocity-dx recon-dx-velocity-dy recon-dy-velocity-dx recon-dy-velocity-dy surf-incident-radiation surf-kinetic-rate-reaction-1 temperature thermal-conductivity-lam thermal-diffc5o2h8 thermal-diffco2 thermal-diffh2o thermal-diffn2 thermal-diffo2 vol-kinetic-rate-reaction-2 x-face-area y-face-area x-velocity y-velocity specific-heat-cp ()

/parallel/timer/usage

/report/summary no

/exit yes
EOF

echo "Created Fluent journal: $JOU"

sbatch \
    --job-name="fluent_${OUT}" \
    --partition="$PARTITION" \
    --nodes=1 \
    --ntasks="$NTASKS" \
    --mem-per-cpu="$MEM_PER_CPU" \
    --time="$TIME_LIMIT" \
    --output="${OUT}_%j.out" \
    --error="${OUT}_%j.err" \
    <<EOF
#!/bin/bash
set -euo pipefail

module load ansys/2025R2

cd "$SUBMIT_DIR/$NEW_FOLDER"

echo "Running on node(s): \$SLURM_NODELIST"
echo "Job ID: \$SLURM_JOB_ID"
echo "Tasks: \$SLURM_NTASKS"
echo "Working directory: \$(pwd)"
echo "Journal file: $JOU"

fluent 2ddp -g -t"\$SLURM_NTASKS" -i "$JOU"
EOF
