#!/bin/bash
set -euo pipefail

OUT=${1:?Usage: ./submit_fluent.sh output_base input_case.cas.h5}
CASE=${2:?Usage: ./submit_fluent.sh output_base input_case.cas.h5}
GX=${GX:-0}
GY=${GY:-9.81}

# To run: ./submit_fluent.sh [run name] [case file] 
# inside the directory with the case file and the NCA_unix.c file
# make executable by doing chmod +x submit_fluent.sh
# Optional environment overrides:
#   FLUENT_NTASKS=8 ./submit_fluent.sh run1 SYS-4.cas.h5
#   FLUENT_TIME=8:00:00 ./submit_fluent.sh run1 SYS-4.cas.h5
NTASKS=${FLUENT_NTASKS:-8}
TIME_LIMIT=${FLUENT_TIME:-24:00:00}
PARTITION=${FLUENT_PARTITION:-engineering}
MEM_PER_CPU=${FLUENT_MEM_PER_CPU:-1000}

SUBMIT_DIR=$(pwd)
CASE_ABS=$(readlink -f "$CASE")
CASE_LOCAL=$(basename "$CASE_ABS")

JOU="${OUT}.jou"
FINAL_CASE_DATA="${OUT}.cas.h5"
S2S_FILE="${OUT}.s2s.h5"
NEW_FOLDER="${OUT}_files"


if [[ ! -f "$CASE_ABS" ]]; then
    echo "Error: case file not found: $CASE_ABS" >&2
    exit 1
fi

if [[ ! -f "NCA_unix.c" ]]; then
    echo "Error: NCA_unx.c not found in current directory: $SUBMIT_DIR" >&2
    echo "Run this script from the directory containing NCA_unix.c and your Fluent files." >&2
    exit 1
fi

if [[ -e ${NEW_FOLDER} ]]; then
    echo "Error: run folder already exists: ${NEW_FOLDER}" >&2
    echo "Please remove or choose a different output base." >&2
    exit 1
fi
mkdir -p "$NEW_FOLDER"
cd "$NEW_FOLDER"

cp "$CASE_ABS" .
cp ../NCA_unix.c .

cat > "$JOU" <<EOF
;;; Solution Journal Script for running the NCA Fluent model in batch mode
;;; Auto-generated by submit_fluent.sh
;;; Output base: ${OUT}
;;; Input case: "${CASE_ABS}"
;;; Local case file: "${CASE_LOCAL}"
;;; Gravity: GX=${GX}, GY=${GY}

;; ------Compile and load UDF------------------------------------------------------
/define/user-defined/compiled-functions compile "lib_inlet_fsr" yes "NCA_unix.c" "" ""
/define/user-defined/compiled-functions load "lib_inlet_fsr"

;; ------Read case file------------------------------------------------------------
/define/user-defined/auto-compile-compiled-udfs no
/file/read-case "${CASE_LOCAL}"

;; ------Set gravity---------------------------------------------------------------
/define/operating-conditions/gravity yes ${GX} ${GY}

;; ------Compute View factors------------------------------------------------------
/define/models/radiation/s2s-parameters compute-write-vf "${S2S_FILE}"

;; ------Initialize----------------------------------------------------------------
/solve/initialize/compute-defaults/velocity-inlet inlet
/solve/initialize/initialize-flow
/solve/patch () newbig () temperature 1900
/solve/patch () downstream () species-3 0

;; UDF setup
/define/user-defined/execute-on-demand "check_u_mean::lib_inlet_fsr"

(rp-var-define 'user/v_f_init 0 'real #f)
/define/user-defined/execute-on-demand "set_FSR::lib_inlet_fsr"

(rp-var-define 'user/alpha 0.5 'real #f)
/define/user-defined/execute-on-demand "set_alpha::lib_inlet_fsr"

;; ------Solve---------------------------------------------------------------------
;;/solve/iterate 50 
/solve/iterate 75000

;; ------Write output case and data -----------------------------------------------
/file/write-case-data "${FINAL_CASE_DATA}"

/file/export/cgns "${FINAL_CASE_DATA}" full-domain yes yes x-coordinate y-coordinate c5h8o2-n-deposition-rate cell-id cell-volume co2 h2o n2 o2 c5o2h8 dco2-dx dco2-dy dh2o-dx dh2o-dy dn2-dx dn2-dy do2-dx do2-dy dc5o2h8-dx dc5o2h8-dy density dt-dx dt-dy heat-flux pressure rad-heat-flux recon-dp-dx recon-dp-dy recon-dt-dx recon-dt-dy recon-dx-velocity-dx recon-dx-velocity-dy recon-dy-velocity-dx recon-dy-velocity-dy surf-incident-radiation surf-kinetic-rate-reaction-1 temperature thermal-conductivity-lam thermal-diffc5o2h8 thermal-diffco2 thermal-diffh2o thermal-diffn2 thermal-diffo2 vol-kinetic-rate-reaction-2 x-face-area y-face-area x-velocity y-velocity specific-heat-cp ()

/parallel/timer/usage

/report/summary no

/exit yes
EOF

echo "Created Fluent journal: $JOU"

sbatch \
    --job-name="fluent_${OUT}" \
    --partition="$PARTITION" \
    --nodes=1 \
    --ntasks="$NTASKS" \
    --mem-per-cpu="$MEM_PER_CPU" \
    --time="$TIME_LIMIT" \
    --output="${OUT}_%j.out" \
    --error="${OUT}_%j.err" \
    <<EOF
#!/bin/bash
set -euo pipefail

module load ansys/2025R2

cd "$SUBMIT_DIR/$NEW_FOLDER"

echo "Running on node(s): \$SLURM_NODELIST"
echo "Job ID: \$SLURM_JOB_ID"
echo "Tasks: \$SLURM_NTASKS"
echo "Working directory: \$(pwd)"
echo "Journal file: $JOU"

fluent 2ddp -g -t"\$SLURM_NTASKS" -i "$JOU"
EOF